"""Code generation for models, APIs, and deployments."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def _schema_to_pydantic_fields(schema) -> str:
    """Convert a Nexora schema to Pydantic field definitions."""
    lines = []
    for col in schema.feature_columns:
        if col.name == schema.target:
            continue
        
        # Map python types
        py_type = "float"
        if col.dtype_str.startswith("int"):
            py_type = "int"
        elif col.dtype_str.startswith("bool"):
            py_type = "bool"
        elif col.dtype_str in ("object", "category", "string"):
            py_type = "str"
            
        lines.append(f"    {col.name}: {py_type}")
    return "\n".join(lines)


def _schema_to_streamlit_inputs(schema) -> str:
    """Convert a Nexora schema to Streamlit input widgets."""
    lines = []
    for col in schema.feature_columns:
        if col.name == schema.target:
            continue
            
        if col.dtype_str in ("object", "category", "string"):
            # Mock a text input or selectbox. In reality we'd pull unique values.
            lines.append(f'        "{col.name}": st.text_input("{col.name}"),')
        elif col.dtype_str.startswith("int"):
            lines.append(f'        "{col.name}": st.number_input("{col.name}", step=1),')
        else:
            lines.append(f'        "{col.name}": st.number_input("{col.name}"),')
            
    return "\n".join(lines)


def generate_python_script(report: NexoraReport, model_name: str | None = None) -> str:
    """Generate a standalone Python script to run the model."""
    target_model = model_name or report.best_model
    
    code = f'''"""Generated by Nexora.
Task: {report.task_type}
Model: {target_model}
Score: {report.best_score:.4f} ({report.best_score_label})
"""

import pandas as pd
import joblib

# Note: For exact reproducible preprocessing, we load the trained pipeline.
# The pipeline handles all imputation, scaling, encoding, and the final estimator.

def predict(input_data: dict | pd.DataFrame) -> list:
    """Run predictions using the trained Nexora pipeline."""
    # Ensure input is a DataFrame
    if isinstance(input_data, dict):
        df = pd.DataFrame([input_data])
    else:
        df = input_data
        
    # Load pipeline
    try:
        pipeline = joblib.load("pipeline.pkl")
    except FileNotFoundError:
        raise FileNotFoundError("pipeline.pkl not found. Make sure to save it alongside this script.")
        
    return pipeline.predict(df).tolist()

if __name__ == "__main__":
    # Example usage
    sample_data = {{
{_schema_to_streamlit_inputs(report.schema).replace('st.text_input("', '"').replace('"),', '",').replace('st.number_input("', '0.0, # ').replace('", step=1),', '').replace('"),', '')}
    }}
    
    # You will need actual default values for the sample above to run successfully.
    print("Prediction:", predict(sample_data))
'''
    return code


def generate_fastapi_app(report: NexoraReport) -> str:
    """Generate a FastAPI app script."""
    
    fields = _schema_to_pydantic_fields(report.schema)
    
    code = f'''"""FastAPI service generated by Nexora."""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pandas as pd
import joblib

app = FastAPI(
    title="Nexora Model API",
    description="Auto-generated predictive API for {report.target}",
    version="1.0.0"
)

# Load pipeline globally at startup
try:
    pipeline = joblib.load("pipeline.pkl")
except Exception as e:
    pipeline = None
    print(f"Warning: Could not load pipeline.pkl: {{e}}")

class PredictionInput(BaseModel):
{fields}

class PredictionOutput(BaseModel):
    prediction: float | str | int
    confidence: float | None = None

@app.get("/health")
def health_check():
    return {{"status": "ok", "model_loaded": pipeline is not None}}

@app.post("/predict", response_model=PredictionOutput)
def predict(data: PredictionInput):
    if pipeline is None:
        raise HTTPException(status_code=500, detail="Model pipeline not loaded.")
        
    # Convert input to DataFrame
    df = pd.DataFrame([data.model_dump()])
    
    # Predict
    pred = pipeline.predict(df)[0]
    
    # Calculate confidence if supported
    confidence = None
    if hasattr(pipeline, "predict_proba"):
        proba = pipeline.predict_proba(df)[0]
        confidence = round(float(max(proba)), 4)
        
    # Type cast for JSON serialization
    if hasattr(pred, "item"):
        pred = pred.item()
        
    return {{"prediction": pred, "confidence": confidence}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    return code


def generate_flask_app(report: NexoraReport) -> str:
    """Generate a Flask app script."""
    
    code = f'''"""Flask service generated by Nexora."""

from flask import Flask, request, jsonify
import pandas as pd
import joblib

app = Flask(__name__)

# Load pipeline globally
try:
    pipeline = joblib.load("pipeline.pkl")
except Exception as e:
    pipeline = None
    print(f"Warning: Could not load pipeline.pkl: {{e}}")

@app.route("/health", methods=["GET"])
def health_check():
    return jsonify({{"status": "ok", "model_loaded": pipeline is not None}})

@app.route("/predict", methods=["POST"])
def predict():
    if pipeline is None:
        return jsonify({{"error": "Model pipeline not loaded."}}), 500
        
    try:
        data = request.get_json()
        if not data:
            return jsonify({{"error": "No JSON payload provided."}}), 400
            
        # Convert input to DataFrame
        df = pd.DataFrame([data])
        
        # Predict
        pred = pipeline.predict(df)[0]
        
        # Type cast for JSON serialization
        if hasattr(pred, "item"):
            pred = pred.item()
            
        return jsonify({{"prediction": pred}})
        
    except Exception as e:
        return jsonify({{"error": str(e)}}), 400

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
'''
    return code


def generate_streamlit_app(report: NexoraReport) -> str:
    """Generate a Streamlit dashboard script."""
    
    inputs = _schema_to_streamlit_inputs(report.schema)
    
    code = f'''"""Streamlit app generated by Nexora."""

import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title="Nexora Model Demo", layout="centered")

st.title("Predictive Model App")
st.write("Auto-generated UI for predicting `{report.target}`.")

@st.cache_resource
def load_model():
    try:
        return joblib.load("pipeline.pkl")
    except Exception as e:
        st.error(f"Could not load pipeline.pkl. Please ensure it is in the same directory. Error: {{e}}")
        return None

pipeline = load_model()

with st.form("prediction_form"):
    st.subheader("Input Features")
    
    # Auto-generated input fields
    input_data = {{
{inputs}
    }}
    
    submitted = st.form_submit_button("Predict")
    
if submitted and pipeline is not None:
    # Convert to DataFrame
    df = pd.DataFrame([input_data])
    
    # Predict
    try:
        pred = pipeline.predict(df)[0]
        st.success(f"### Prediction: {{pred}}")
        
        if hasattr(pipeline, "predict_proba"):
            proba = pipeline.predict_proba(df)[0]
            confidence = float(max(proba))
            st.info(f"Confidence: {{confidence:.1%}}")
            
    except Exception as e:
        st.error(f"Prediction failed: {{e}}")
'''
    return code


def generate_dockerfile(report: NexoraReport) -> str:
    """Generate a Dockerfile and requirements."""
    
    dockerfile = f'''# Dockerfile generated by Nexora
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Assuming FastAPI (api.py) is used. Change to app.py if using Flask.
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
'''
    return dockerfile


def generate_mlflow_script(report: NexoraReport) -> str:
    """Generate an MLflow tracking wrapper."""
    
    code = f'''"""MLflow integration generated by Nexora."""

import mlflow
import mlflow.sklearn
import joblib

# Set tracking URI if you have a remote server
# mlflow.set_tracking_uri("http://localhost:5000")

mlflow.set_experiment("Nexora_AutoML")

with mlflow.start_run(run_name="nexora_{report.best_model}"):
    try:
        # Load your trained pipeline
        pipeline = joblib.load("pipeline.pkl")
        
        # Log parameters (you can manually add your hyperparameters here)
        mlflow.log_param("model_type", "{report.best_model}")
        mlflow.log_param("task_type", "{report.task_type}")
        
        # Log the primary score
        mlflow.log_metric("{report.best_score_label}", {report.best_score})
        
        # Save the model to MLflow registry
        mlflow.sklearn.log_model(pipeline, "model")
        print("Successfully logged to MLflow.")
        
    except FileNotFoundError:
        print("Error: pipeline.pkl not found.")
'''
    return code


def generate_gradio_app(report: NexoraReport) -> str:
    """Generate a Gradio app script."""
    
    code = f'''"""Gradio app generated by Nexora."""

import gradio as gr
import pandas as pd
import joblib

# Load pipeline globally
try:
    pipeline = joblib.load("pipeline.pkl")
except Exception as e:
    pipeline = None
    print(f"Warning: Could not load pipeline.pkl: {{e}}")

def predict_fn(*args):
    if pipeline is None:
        return "Error: Model pipeline not loaded."
        
    # Zip feature names with args to create dict
    feature_names = {[col.name for col in report.schema.feature_columns if col.name != report.target]}
    input_data = dict(zip(feature_names, args))
    
    # Convert to DataFrame
    df = pd.DataFrame([input_data])
    
    # Predict
    try:
        pred = pipeline.predict(df)[0]
        result = f"Prediction: {{pred}}"
        
        if hasattr(pipeline, "predict_proba"):
            proba = pipeline.predict_proba(df)[0]
            confidence = float(max(proba))
            result += f"\\nConfidence: {{confidence:.1%}}"
            
        return result
    except Exception as e:
        return f"Prediction failed: {{e}}"

# Define inputs based on schema
inputs = []
for col in {[col.name for col in report.schema.feature_columns if col.name != report.target]}:
    inputs.append(gr.Textbox(label=col))

# Create Gradio interface
demo = gr.Interface(
    fn=predict_fn,
    inputs=inputs,
    outputs="text",
    title="Nexora Predictive Model",
    description="Auto-generated Gradio interface for predicting `{report.target}`."
)

if __name__ == "__main__":
    demo.launch(share=False)
'''
    return code


def generate_github_actions(report: NexoraReport) -> str:
    """Generate a GitHub Actions workflow for training and deployment."""
    return f"""name: Nexora Train and Publish

on:
  push:
    branches:
      - main

jobs:
  train_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install nexora huggingface_hub
        
      - name: Run Nexora Training Script
        env:
          HF_TOKEN: ${{{{ secrets.HF_TOKEN }}}}
        run: |
          python -c "
          from nexora import Nexora
          import pandas as pd
          df = pd.read_csv('data/dataset.csv')
          nx = Nexora(df, target='{report.target}')
          report = nx.run()
          report.publish('my-org/my-nexora-model')
          "
"""

def generate_code_all(report: NexoraReport, output_dir: str | Path):
    """Generate all code variants to a directory."""
    from nexora.export.codegen import (
        generate_python_script, generate_fastapi_app, generate_streamlit_app,
        generate_flask_app, generate_dockerfile, generate_mlflow_script, generate_gradio_app,
        generate_github_actions
    )
    import joblib
    
    out = Path(output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    
    # Save the pipeline
    joblib.dump(report.pipeline, out / "pipeline.pkl")
    
    # Save all scripts
    (out / "model.py").write_text(generate_python_script(report), encoding="utf-8")
    (out / "fastapi_app.py").write_text(generate_fastapi_app(report), encoding="utf-8")
    (out / "streamlit_app.py").write_text(generate_streamlit_app(report), encoding="utf-8")
    (out / "flask_app.py").write_text(generate_flask_app(report), encoding="utf-8")
    (out / "Dockerfile").write_text(generate_dockerfile(report), encoding="utf-8")
    (out / "mlflow_train.py").write_text(generate_mlflow_script(report), encoding="utf-8")
    (out / "gradio_app.py").write_text(generate_gradio_app(report), encoding="utf-8")
    
    # Write Github actions
    github_dir = out / ".github" / "workflows"
    github_dir.mkdir(parents=True, exist_ok=True)
    (github_dir / "nexora_train.yml").write_text(generate_github_actions(report), encoding="utf-8")
    
    # Write basic requirements.txt
    reqs = "pandas\nscikit-learn\njoblib\nfastapi\nuvicorn\npydantic\nstreamlit\nflask\nmlflow\ngradio\n"
    (out / "requirements.txt").write_text(reqs, encoding="utf-8")
