"""Generate Docker deployment files for trained Nexora models."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_docker(
    report: NexoraReport, model_name: str | None = None
) -> tuple[str, str]:
    """Generate Docker deployment files (Dockerfile + requirements.txt).

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Tuple of (dockerfile_content, requirements_content).

    Example:
        `docker_code, reqs = generate_docker(report)`
    """

    result, spec = _resolve_model(report, model_name)
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    dockerfile = f"""# ────────────────────────────────────────────────────────────────
# Dockerfile: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset}
# ────────────────────────────────────────────────────────────────

FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy model and requirements
COPY model.pkl /app/
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py /app/

# Expose port for FastAPI/Flask
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

# Run the application
CMD ["python", "app.py"]
"""

    requirements = """# ────────────────────────────────────────────────────────────────
# requirements.txt
# Generated by Nexora
# Install with: pip install -r requirements.txt
# ────────────────────────────────────────────────────────────────

# Core dependencies
pandas>=2.0
numpy>=1.24
scikit-learn>=1.3
joblib>=1.3

# Web framework (choose one)
fastapi>=0.104  # For FastAPI apps
# flask>=2.3    # For Flask apps
# streamlit>=1.30  # For Streamlit apps
uvicorn>=0.24

# Model training (if needed)
xgboost>=2.0
lightgbm>=4.0
catboost>=1.2

# Utilities
pydantic>=2.0
python-multipart>=0.0.6
"""

    return dockerfile, requirements


def _resolve_model(
    report: NexoraReport, model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
