"""Generate FastAPI applications for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_fastapi(report: "NexoraReport", model_name: str | None = None) -> str:
    """Generate a complete FastAPI application for model serving.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Complete FastAPI application code (standalone, no Nexora imports).

    Example:
        `code = generate_fastapi(report, "XGBRegressor")`
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score
    model_id = result.model_id

    # Generate Pydantic input model from feature columns
    pydantic_fields = _pydantic_fields(schema.numeric_features, schema.categorical_features)
    
    # Generate imports for model class
    model_import = f"from {spec.import_path} import {spec.class_name}"

    example_record = ", ".join(f'"{col}": 0' for col in schema.feature_columns[:3])
    example_record_2 = ", ".join(f'"{col}": 42.5' if col in schema.numeric_features else f'"{col}": "value"' for col in schema.feature_columns[:3])
    
    keys_desc = ", ".join(schema.feature_columns)
    
    return f'''# ────────────────────────────────────────────────────────────────
# FastAPI Model Server: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ────────────────────────────────────────────────────────────────

import pickle
from pathlib import Path
from typing import Dict, List

import pandas as pd
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

{model_import}
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


# ─ Configuration ─────────────────────────────────────────
TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}

# nexora: auto-detected feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}

# nexora: auto-detected numeric columns
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}

# nexora: auto-detected categorical columns
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}

# nexora: model metadata captured from leaderboard
MODEL_ID = {result.model_id!r}
MODEL_NAME = {result.model_name!r}
PRIMARY_METRIC = {metric!r}
PRIMARY_SCORE = {score}


# ─ Pydantic Request/Response Models ──────────────────────
class PredictionRequest(BaseModel):
    """Input request for batch predictions."""

    data: List[Dict[str, float | str | None]] = Field(
        ...,
        description="List of records with keys: {keys_desc}",
        example=[{{{example_record}}}],
    )

    class Config:
        json_schema_extra = {{
            "example": {{
                "data": [{{{example_record_2}}}]
            }}
        }}


class PredictionResponse(BaseModel):
    """Output response for predictions."""

    predictions: List[float | int]
    model_name: str
    task_type: str
    n_samples: int
    feature_columns: List[str]

    class Config:
        json_schema_extra = {{
            "example": {{
                "predictions": [42.5, 37.2, 51.0],
                "model_name": "{result.model_name}",
                "task_type": "{report.task_type}",
                "n_samples": 3,
                "feature_columns": FEATURE_COLUMNS,
            }}
        }}


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    model: str
    metric: str
    score: float
    features: int
    task_type: str


# ─ Initialize FastAPI ────────────────────────────────────
app = FastAPI(
    title="Nexora Model Server",
    description=f"Production inference for {{MODEL_NAME}} ({{PRIMARY_METRIC}}={{PRIMARY_SCORE:.4f}})",
    version="0.1.0",
)

# Global model pipeline
_pipeline: Pipeline | None = None


def _load_model() -> Pipeline:
    """Load or cache the fitted model pipeline."""

    global _pipeline
    if _pipeline is None:
        # In production, load from pickle or model registry
        # For now, this is a placeholder that assumes model.pkl exists
        model_path = Path(__file__).parent / "model.pkl"
        if model_path.exists():
            with open(model_path, "rb") as f:
                _pipeline = pickle.load(f)
        else:
            raise RuntimeError(
                f"Model not found at {{model_path}}. "
                "Save the pipeline with: pickle.dump(report.pipeline, open('model.pkl', 'wb'))"
            )
    return _pipeline


def _build_preprocessor() -> ColumnTransformer:
    """Reconstruct the preprocessing pipeline."""

    transformers = []
    if NUMERIC_FEATURES:
        transformers.append(
            (
                "numeric",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", StandardScaler()),
                ]),
                NUMERIC_FEATURES,
            )
        )
    if CATEGORICAL_FEATURES:
        transformers.append(
            (
                "categorical",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
                ]),
                CATEGORICAL_FEATURES,
            )
        )
    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        verbose_feature_names_out=False,
    )


# ─ API Endpoints ─────────────────────────────────────────

@app.get("/", tags=["Info"])
def read_root() -> Dict[str, str]:
    """Root endpoint."""

    return {{
        "service": "Nexora Model Server",
        "model": MODEL_NAME,
        "metric": PRIMARY_METRIC,
        "score": str(PRIMARY_SCORE),
    }}


@app.get("/health", response_model=HealthResponse, tags=["Health"])
def health_check() -> HealthResponse:
    """Health check endpoint.

    Returns:
        Health status with model metadata.
    """

    try:
        _load_model()
        return HealthResponse(
            status="ok",
            model=MODEL_NAME,
            metric=PRIMARY_METRIC,
            score=PRIMARY_SCORE,
            features=len(FEATURE_COLUMNS),
            task_type=TASK_TYPE,
        )
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"Model loading failed: {{str(e)}}",
        )


@app.post("/predict", response_model=PredictionResponse, tags=["Prediction"])
def predict(request: PredictionRequest) -> PredictionResponse:
    """Make predictions on new data.

    Args:
        request: Batch prediction request with feature data.

    Returns:
        Predictions from the best model.

    Raises:
        HTTPException: If data is invalid or model loading fails.
    """

    try:
        # Load model
        pipeline = _load_model()

        # Convert to DataFrame
        df = pd.DataFrame(request.data)

        # Validate columns
        missing = [col for col in FEATURE_COLUMNS if col not in df.columns]
        if missing:
            raise ValueError(f"Missing required columns: {{', '.join(missing)}}")

        # Select features in correct order
        X = df[FEATURE_COLUMNS]

        # Make predictions
        predictions = pipeline.predict(X).tolist()

        return PredictionResponse(
            predictions=predictions,
            model_name=MODEL_NAME,
            task_type=TASK_TYPE,
            n_samples=len(predictions),
            feature_columns=FEATURE_COLUMNS,
        )

    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=f"Prediction failed: {{str(e)}}",
        )


@app.post("/predict/proba", tags=["Prediction"])
def predict_proba(request: PredictionRequest) -> Dict:
    """Get prediction probabilities (classification only).

    Args:
        request: Batch prediction request.

    Returns:
        Predicted probabilities for each class.

    Raises:
        HTTPException: If task is not classification.
    """

    if TASK_TYPE != "classification":
        raise HTTPException(
            status_code=400,
            detail="Probability predictions only available for classification models.",
        )

    try:
        pipeline = _load_model()
        df = pd.DataFrame(request.data)

        missing = [col for col in FEATURE_COLUMNS if col not in df.columns]
        if missing:
            raise ValueError(f"Missing columns: {{', '.join(missing)}}")

        X = df[FEATURE_COLUMNS]
        model = pipeline.named_steps["model"]

        if not hasattr(model, "predict_proba"):
            raise ValueError("Model does not support probability predictions.")

        probas = pipeline.predict_proba(X).tolist()

        return {{
            "task_type": TASK_TYPE,
            "model": MODEL_NAME,
            "n_samples": len(probas),
            "probabilities": probas,
        }}

    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=f"Proba prediction failed: {{str(e)}}",
        )


# ─ Main Entry Point ──────────────────────────────────────

if __name__ == "__main__":
    import sys

    host = sys.argv[1] if len(sys.argv) > 1 else "0.0.0.0"
    port = int(sys.argv[2]) if len(sys.argv) > 2 else 8000

    print(f"Starting Nexora Model Server: {{MODEL_NAME}} ({{PRIMARY_METRIC}}={{PRIMARY_SCORE:.4f}})")
    print(f"Listening on http://{{host}}:{{port}}")
    print(f"API docs available at http://{{host}}:{{port}}/docs")

    uvicorn.run(
        app,
        host=host,
        port=port,
    )
'''


# ─ Internal Helper Functions ────────────────────────────

def _resolve_model(
    report: "NexoraReport", model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec


def _pydantic_fields(
    numeric_features: list[str], categorical_features: list[str]
) -> str:
    """Generate Pydantic field definitions (placeholder for future use)."""

    # This could be expanded to generate more detailed Pydantic models
    # with per-field validation, but the current generic Dict approach works well
    return ""
