"""Generate Flask applications for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_flask(report: "NexoraReport", model_name: str | None = None) -> str:
    """Generate a complete Flask application for model serving.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Complete Flask application code (standalone, no Nexora imports).

    Example:
        `code = generate_flask(report)` → Run with `flask run` or `python app.py`
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    return f'''# ────────────────────────────────────────────────────────────────
# Flask Model Server: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ────────────────────────────────────────────────────────────────

import pickle
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, request, render_string
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


# ─ Configuration ─────────────────────────────────────────
TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}
MODEL_NAME = {result.model_name!r}
PRIMARY_METRIC = {metric!r}
PRIMARY_SCORE = {score}

FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}


# ─ Flask App ─────────────────────────────────────────────
app = Flask(__name__)
app.config["JSON_SORT_KEYS"] = False

_pipeline = None


def get_model() -> Pipeline:
    """Load or get cached model."""

    global _pipeline
    if _pipeline is None:
        model_path = Path(__file__).parent / "model.pkl"
        if not model_path.exists():
            raise RuntimeError(f"Model not found: {{model_path}}")
        with open(model_path, "rb") as f:
            _pipeline = pickle.load(f)
    return _pipeline


# ─ Routes ────────────────────────────────────────────────

@app.route("/", methods=["GET"])
def index():
    """Root endpoint with model info."""

    return jsonify({{
        "service": "Nexora Flask Server",
        "model": MODEL_NAME,
        "metric": PRIMARY_METRIC,
        "score": float(PRIMARY_SCORE),
        "features": len(FEATURE_COLUMNS),
        "task_type": TASK_TYPE,
    }})


@app.route("/health", methods=["GET"])
def health():
    """Health check endpoint."""

    try:
        get_model()
        return jsonify({{
            "status": "ok",
            "model": MODEL_NAME,
        }})
    except Exception as e:
        return jsonify({{"status": "error", "message": str(e)}}), 503


@app.route("/predict", methods=["POST"])
def predict():
    """Make predictions on new data.

    Expected JSON: {{"data": [{{"col1": value1, "col2": value2, ...}}]}}
    """

    try:
        request_data = request.get_json()
        if not request_data or "data" not in request_data:
            return jsonify({{"error": "Missing 'data' field in request"}}), 400

        records = request_data["data"]
        if not isinstance(records, list):
            records = [records]

        # Convert to DataFrame
        df = pd.DataFrame(records)

        # Validate columns
        missing = [col for col in FEATURE_COLUMNS if col not in df.columns]
        if missing:
            return jsonify({{"error": f"Missing columns: {{', '.join(missing)}}"}}), 400

        # Make predictions
        pipeline = get_model()
        X = df[FEATURE_COLUMNS]
        predictions = pipeline.predict(X).tolist()

        return jsonify({{
            "predictions": predictions,
            "model": MODEL_NAME,
            "n_samples": len(predictions),
        }})

    except Exception as e:
        return jsonify({{"error": str(e)}}), 400


@app.route("/predict/proba", methods=["POST"])
def predict_proba():
    """Get prediction probabilities (classification only)."""

    if TASK_TYPE != "classification":
        return jsonify({{"error": "Probabilities only for classification"}}), 400

    try:
        request_data = request.get_json()
        records = request_data.get("data", [])
        if not isinstance(records, list):
            records = [records]

        df = pd.DataFrame(records)
        pipeline = get_model()
        X = df[FEATURE_COLUMNS]
        probas = pipeline.predict_proba(X).tolist()

        return jsonify({{
            "probabilities": probas,
            "model": MODEL_NAME,
            "n_samples": len(probas),
        }})

    except Exception as e:
        return jsonify({{"error": str(e)}}), 400


# ─ Error Handlers ────────────────────────────────────────

@app.errorhandler(404)
def not_found(error):
    return jsonify({{"error": "Endpoint not found"}}), 404


@app.errorhandler(500)
def internal_error(error):
    return jsonify({{"error": "Internal server error"}}), 500


# ─ Main Entry Point ──────────────────────────────────────

if __name__ == "__main__":
    print(f"Starting Flask Model Server: {{MODEL_NAME}}")
    print("Visit http://localhost:5000 for API docs")
    app.run(debug=False, host="0.0.0.0", port=5000)
'''


def _resolve_model(
    report: "NexoraReport", model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
