"""Generate MLflow tracking code for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_mlflow(report: "NexoraReport", model_name: str | None = None) -> str:
    """Generate MLflow experiment tracking code.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Python script with MLflow tracking integration.

    Example:
        `code = generate_mlflow(report)` → Tracks experiments in MLflow UI
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    return f'''# ────────────────────────────────────────────────────────────────
# MLflow Tracking: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ────────────────────────────────────────────────────────────────

import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score, mean_squared_error, mean_absolute_error
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from {spec.import_path} import {spec.class_name}


# ─ Configuration ─────────────────────────────────────────
TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}
RANDOM_STATE = 42

# nexora: auto-detected feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}

# nexora: model metadata from leaderboard
MODEL_NAME = {result.model_name!r}
PRIMARY_METRIC = {metric!r}
PRIMARY_SCORE = {score}


# ─ MLflow Configuration ──────────────────────────────────
mlflow.set_experiment("{result.model_name} Training")
mlflow.set_tracking_uri("http://localhost:5000")  # Change to your MLflow server


def build_preprocessor():
    transformers = []
    if NUMERIC_FEATURES:
        transformers.append((
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            NUMERIC_FEATURES,
        ))
    if CATEGORICAL_FEATURES:
        transformers.append((
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]),
            CATEGORICAL_FEATURES,
        ))
    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        verbose_feature_names_out=False,
    )


def train_and_log():
    """Train model and log to MLflow."""

    with mlflow.start_run(run_name=MODEL_NAME):
        # Load data
        df = pd.read_csv("data.csv", low_memory=False)
        X = df[FEATURE_COLUMNS]
        y = df[TARGET]

        # Split data
        if TASK_TYPE == "classification":
            stratify = y if y.value_counts(dropna=False).min() >= 2 else None
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=stratify
            )
        else:
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=RANDOM_STATE
            )

        # Log parameters
        mlflow.log_params({{
            "model": MODEL_NAME,
            "task_type": TASK_TYPE,
            "train_size": len(X_train),
            "test_size": len(X_test),
            "n_features": len(FEATURE_COLUMNS),
            **{{f"param_{{k}}": v for k, v in {pprint.pformat(spec.params, width=88)}.items()}},
        }})

        # Build and train pipeline
        preprocessor = build_preprocessor()
        model = {spec.class_name}(**{pprint.pformat(spec.params, width=88)})
        
        pipeline = Pipeline([
            ("preprocess", preprocessor),
            ("model", model),
        ])
        
        pipeline.fit(X_train, y_train)
        predictions = pipeline.predict(X_test)

        # Calculate metrics
        if TASK_TYPE == "classification":
            accuracy = accuracy_score(y_test, predictions)
            mlflow.log_metrics({{"accuracy": accuracy}})
            print(f"Accuracy: {{accuracy:.4f}}")
        else:
            r2 = r2_score(y_test, predictions)
            rmse = np.sqrt(mean_squared_error(y_test, predictions))
            mae = mean_absolute_error(y_test, predictions)
            mlflow.log_metrics({{
                "r2": r2,
                "rmse": rmse,
                "mae": mae,
            }})
            print(f"R²: {{r2:.4f}}, RMSE: {{rmse:.4f}}, MAE: {{mae:.4f}}")

        # Log model
        mlflow.sklearn.log_model(pipeline, "model")

        # Log dataset info
        mlflow.log_dict({{"rows": len(df), "features": len(FEATURE_COLUMNS)}}, "data_info")

        print(f"✅ Logged to MLflow: {{mlflow.get_run().info.run_id}}")
        
        return pipeline


if __name__ == "__main__":
    print("Training with MLflow tracking...")
    print("View results at: http://localhost:5000")
    
    pipeline = train_and_log()
'''


def _resolve_model(
    report: "NexoraReport", model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
