"""Generate Jupyter notebooks for trained Nexora models."""

from __future__ import annotations

import json
import pprint
from pathlib import Path
from typing import TYPE_CHECKING, Any

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_notebook(report: "NexoraReport", model_name: str | None = None) -> str:
    """Generate a Jupyter notebook (.ipynb) for model training and prediction.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        JSON string for .ipynb file.

    Example:
        `nb_json = generate_notebook(report)`
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    cells: list[dict[str, Any]] = []

    # Title and overview
    cells.append(_markdown_cell(f"""# {result.model_name} Model Notebook

**Generated by Nexora** | https://nexoraprediction.netlify.app

- **Model**: {result.model_name}
- **Metric**: {metric} = {score:.4f}
- **Dataset**: {dataset}
- **Rows**: {report.profile.rows}
- **Features**: {len(schema.feature_columns)}

This notebook demonstrates training and using the best model from Nexora."""))

    # Setup
    cells.append(_markdown_cell("## 1. Setup & Imports"))
    cells.append(_code_cell('''import pandas as pd
import numpy as np
import pickle
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score, mean_squared_error, mean_absolute_error
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
'''))

    # Configuration
    cells.append(_markdown_cell("## 2. Configuration"))

    config_code = f'''# nexora: auto-detected feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}

TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}
RANDOM_STATE = 42
'''

    cells.append(_code_cell(config_code))

    # Load data
    cells.append(_markdown_cell("## 3. Load Data"))
    cells.append(_code_cell('''# Load training data
df = pd.read_csv("data.csv", low_memory=False)
print(f"Dataset shape: {df.shape}")
df.head()
'''))

    # Preprocessing
    cells.append(_markdown_cell("## 4. Preprocessing Pipeline"))
    cells.append(_code_cell('''def build_preprocessor():
    transformers = []
    
    if NUMERIC_FEATURES:
        transformers.append((
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            NUMERIC_FEATURES,
        ))
    
    if CATEGORICAL_FEATURES:
        transformers.append((
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]),
            CATEGORICAL_FEATURES,
        ))
    
    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        verbose_feature_names_out=False,
    )

preprocessor = build_preprocessor()
print("Preprocessing pipeline created")
'''))

    # Training
    cells.append(_markdown_cell("## 5. Train Model"))
    cells.append(_code_cell(f'''from {spec.import_path} import {spec.class_name}

X = df[FEATURE_COLUMNS]
y = df[TARGET]

if TASK_TYPE == "classification":
    stratify = y if y.value_counts(dropna=False).min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=stratify
    )
else:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE
    )

# nexora: tuned parameters from leaderboard
model = {spec.class_name}(**{pprint.pformat(spec.params, width=88)})

pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", model),
])

pipeline.fit(X_train, y_train)
predictions = pipeline.predict(X_test)

print(f"Model trained successfully!")
'''))

    # Evaluation
    cells.append(_markdown_cell("## 6. Evaluation"))

    if report.task_type == "classification":
        eval_code = '''accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.4f}")

# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))
'''
    else:
        eval_code = '''r2 = r2_score(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
mae = mean_absolute_error(y_test, predictions)

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
'''

    cells.append(_code_cell(eval_code))

    # Save model
    cells.append(_markdown_cell("## 7. Save Model"))
    cells.append(_code_cell('''# Save the fitted pipeline
with open("model.pkl", "wb") as f:
    pickle.dump(pipeline, f)

print("Model saved to model.pkl")
'''))

    # Prediction
    cells.append(_markdown_cell("## 8. Make Predictions"))
    cells.append(_code_cell('''# Example: predict on new data
new_data = pd.DataFrame([X_test.iloc[0].to_dict()])
new_prediction = pipeline.predict(new_data)

print(f"Prediction: {new_prediction[0]}")
print(f"Features: {new_data.to_dict()}")
'''))

    # Build notebook structure
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 2,
    }

    return json.dumps(notebook, indent=2)


def _markdown_cell(content: str) -> dict[str, Any]:
    """Create a markdown cell."""

    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [content],
    }


def _code_cell(content: str) -> dict[str, Any]:
    """Create a code cell."""

    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [content],
    }


def _resolve_model(
    report: "NexoraReport", model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
