"""Generate sklearn Pipeline objects for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_pipeline(report: "NexoraReport", model_name: str | None = None) -> str:
    """Generate code to recreate the sklearn Pipeline programmatically.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Python script that creates a fitted Pipeline object.

    Example:
        `code = generate_pipeline(report)` → Returns Pipeline creation code
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    return f'''# ────────────────────────────────────────────────────────────────
# sklearn Pipeline: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ────────────────────────────────────────────────────────────────

import pickle
from pathlib import Path

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from {spec.import_path} import {spec.class_name}


# ─ Configuration ─────────────────────────────────────────
TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}

# nexora: auto-detected feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}


# ─ Pipeline Factory ─────────────────────────────────────

def create_pipeline() -> Pipeline:
    """Create the Nexora preprocessing + model pipeline.

    Returns:
        Unfitted sklearn Pipeline with preprocessing and model.

    Example:
        pipeline = create_pipeline()
        pipeline.fit(X_train, y_train)
        predictions = pipeline.predict(X_test)
    """

    # ─ Preprocessing ─────────────────────────────────────

    transformers = []

    if NUMERIC_FEATURES:
        transformers.append((
            "numeric",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]),
            NUMERIC_FEATURES,
        ))

    if CATEGORICAL_FEATURES:
        transformers.append((
            "categorical",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
            ]),
            CATEGORICAL_FEATURES,
        ))

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        verbose_feature_names_out=False,
    )

    # ─ Model ─────────────────────────────────────────────

    # nexora: tuned parameters from leaderboard
    model = {spec.class_name}(**{pprint.pformat(spec.params, width=88)})

    # ─ Full Pipeline ─────────────────────────────────────

    pipeline = Pipeline([
        ("preprocess", preprocessor),
        ("model", model),
    ])

    return pipeline


# ─ Usage Example ─────────────────────────────────────────

if __name__ == "__main__":
    # Create pipeline
    pipeline = create_pipeline()
    print(f"Pipeline created: {{pipeline}}")

    # Load data
    df = pd.read_csv("data.csv", low_memory=False)
    X = df[FEATURE_COLUMNS]
    y = df[TARGET]

    # Train
    pipeline.fit(X, y)
    print("Pipeline fitted successfully!")

    # Predict
    predictions = pipeline.predict(X.head(5))
    print(f"Predictions: {{predictions}}")

    # Save
    with open("pipeline.pkl", "wb") as f:
        pickle.dump(pipeline, f)
    print("Pipeline saved to pipeline.pkl")

    # Load
    with open("pipeline.pkl", "rb") as f:
        loaded_pipeline = pickle.load(f)
    print("Pipeline loaded successfully!")
'''


def _resolve_model(
    report: "NexoraReport", model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
