"""Generate standalone Python scripts for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_script(report: NexoraReport, model_name: str | None = None) -> str:
    """Generate standalone Python code for a trained leaderboard model.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Standalone Python script text with no Nexora imports.

    Example:
        `code = generate_script(report, "RandomForestRegressor")`
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score
    params = pprint.pformat(spec.params, width=88, sort_dicts=True)
    scoring = _scoring_block(report.task_type)
    split = _split_block(report.task_type)
    transformers = _transformer_block(
        schema.numeric_features, schema.categorical_features
    )

    return f"""# ------------------------------------------------------------
# Best model: {result.model_name} | {metric}={score:.3f}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ------------------------------------------------------------

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, f1_score, mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from {spec.import_path} import {spec.class_name}


DATASET = {dataset!r}
TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}
RANDOM_STATE = 42

# nexora: auto-detected usable feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}

# nexora: auto-detected numeric preprocessing columns
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}

# nexora: auto-detected categorical preprocessing columns
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}

# nexora: auto-detected columns excluded from training
DROP_COLUMNS = {pprint.pformat(schema.dropped_columns, width=88)}


def build_preprocessor():
    transformers = []
{transformers}
    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        verbose_feature_names_out=False,
    )


def main():
    df = pd.read_csv(DATASET, low_memory=False)
    df = df.dropna(subset=[TARGET]).drop_duplicates().reset_index(drop=True)

    missing = [column for column in FEATURE_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(f"Missing required feature columns: {{missing}}")

    X = df[FEATURE_COLUMNS]
    y = df[TARGET]

{split}
    preprocessor = build_preprocessor()

    # nexora: model parameters captured from the leaderboard run
    model = {spec.class_name}(**{params})

    pipeline = Pipeline([
        ("preprocess", preprocessor),
        ("model", model),
    ])
    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

{scoring}


main()
"""


def _resolve_model(
    report: NexoraReport, model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec


def _transformer_block(numeric: list[str], categorical: list[str]) -> str:
    lines: list[str] = []
    if numeric:
        lines.extend(
            [
                "    transformers.append((",
                '        "numeric",',
                "        Pipeline([",
                '            ("imputer", SimpleImputer(strategy="median")),',
                '            ("scaler", StandardScaler()),',
                "        ]),",
                "        NUMERIC_FEATURES,",
                "    ))",
            ]
        )
    if categorical:
        lines.extend(
            [
                "    transformers.append((",
                '        "categorical",',
                "        Pipeline([",
                '            ("imputer", SimpleImputer(strategy="most_frequent")),',
                '            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),',
                "        ]),",
                "        CATEGORICAL_FEATURES,",
                "    ))",
            ]
        )
    return "\n".join(lines)


def _split_block(task_type: str) -> str:
    if task_type == "classification":
        return """    stratify = y if y.value_counts(dropna=False).min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=RANDOM_STATE,
        stratify=stratify,
    )"""
    return """    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=RANDOM_STATE,
    )"""


def _scoring_block(task_type: str) -> str:
    if task_type == "classification":
        return """    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions, average="weighted", zero_division=0)
    print(f"accuracy={accuracy:.4f}")
    print(f"f1={f1:.4f}")"""
    return """    mae = mean_absolute_error(y_test, predictions)
    rmse = mean_squared_error(y_test, predictions) ** 0.5
    r2 = r2_score(y_test, predictions)
    print(f"r2={r2:.4f}")
    print(f"rmse={rmse:.4f}")
    print(f"mae={mae:.4f}")"""
