"""Generate Streamlit interactive dashboards for trained Nexora models."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import TYPE_CHECKING

from nexora.types import ModelResult, ModelSpec

if TYPE_CHECKING:
    from nexora.report import NexoraReport


def generate_streamlit(report: NexoraReport, model_name: str | None = None) -> str:
    """Generate a complete Streamlit application for interactive model prediction.

    Args:
        report: Trained Nexora report.
        model_name: Optional model id, model name, or estimator class name.

    Returns:
        Complete Streamlit application code (standalone, ready to run).

    Example:
        `code = generate_streamlit(report)` → Run with `streamlit run app.py`
    """

    result, spec = _resolve_model(report, model_name)
    schema = report.schema
    dataset = Path(report.source_name).name
    metric = report.best_score_label if model_name is None else result.primary_metric
    score = result.primary_score

    # Build input fields based on feature types
    numeric_cols = schema.numeric_features
    categorical_cols = schema.categorical_features

    numeric_fields = _numeric_input_block(numeric_cols)
    categorical_fields = _categorical_input_block(categorical_cols)

    return f'''# ────────────────────────────────────────────────────────────────
# Streamlit Dashboard: {result.model_name}
# Generated by Nexora | https://nexoraprediction.netlify.app
# Model: {result.model_name} | {metric}={score:.3f}
# Dataset: {dataset} | {report.profile.rows} rows | {len(schema.feature_columns)} features
# ────────────────────────────────────────────────────────────────

import pickle
from pathlib import Path

import pandas as pd
import streamlit as st
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


# ─ Configuration ─────────────────────────────────────────
st.set_page_config(
    page_title="{result.model_name}",
    page_icon="🤖",
    layout="wide",
)

TARGET = {schema.target!r}
TASK_TYPE = {report.task_type!r}
MODEL_NAME = {result.model_name!r}
PRIMARY_METRIC = {metric!r}
PRIMARY_SCORE = {score}

# nexora: auto-detected feature columns
FEATURE_COLUMNS = {pprint.pformat(schema.feature_columns, width=88)}
NUMERIC_FEATURES = {pprint.pformat(schema.numeric_features, width=88)}
CATEGORICAL_FEATURES = {pprint.pformat(schema.categorical_features, width=88)}


# ─ Session State & Caching ───────────────────────────────
@st.cache_resource
def load_model() -> Pipeline:
    """Load trained model from pickle file."""

    model_path = Path(__file__).parent / "model.pkl"
    if not model_path.exists():
        st.error(f"Model file not found: {{model_path}}")
        st.stop()
    
    with open(model_path, "rb") as f:
        return pickle.load(f)


# ─ Page Layout ───────────────────────────────────────────
st.title(f"🤖 {{MODEL_NAME}} Prediction Dashboard")

st.markdown(f"""
**Model Performance**: {{PRIMARY_METRIC}} = **{{PRIMARY_SCORE:.4f}}**

This interactive dashboard lets you make predictions using the best trained model.
Adjust the input values below and click "Predict" to see results.
""")

# Tabs for different prediction modes
tab1, tab2, tab3 = st.tabs(["Single Prediction", "Batch Upload", "Model Info"])

with tab1:
    st.subheader("📊 Make a Single Prediction")
    
    # Two-column layout for input fields
    col_left, col_right = st.columns(2)
    
    input_data = {{}}
    
    # Numeric inputs
    numeric_inputs = {{}}
{numeric_fields}
    
    # Categorical inputs
    categorical_inputs = {{}}
{categorical_fields}
    
    # Combine inputs
    input_data.update(numeric_inputs)
    input_data.update(categorical_inputs)
    
    # Prediction button
    if st.button("🔮 Predict", type="primary"):
        try:
            pipeline = load_model()
            df_input = pd.DataFrame([input_data])
            
            # Validate columns
            missing = [col for col in FEATURE_COLUMNS if col not in df_input.columns]
            if missing:
                st.error(f"Missing columns: {{', '.join(missing)}}")
            else:
                X = df_input[FEATURE_COLUMNS]
                prediction = pipeline.predict(X)[0]
                
                # Display prediction
                st.success(f"✅ Prediction: **{{prediction}}**")
                
                # Show confidence for classification
                if TASK_TYPE == "classification" and hasattr(pipeline.named_steps["model"], "predict_proba"):
                    try:
                        probas = pipeline.predict_proba(X)[0]
                        proba_dict = {{str(i): round(p, 4) for i, p in enumerate(probas)}}
                        st.bar_chart(proba_dict)
                    except:
                        pass
                
                # Show input features
                with st.expander("📋 View Input Features"):
                    st.dataframe(df_input)
        
        except Exception as e:
            st.error(f"❌ Prediction failed: {{str(e)}}")


with tab2:
    st.subheader("📤 Batch Predictions from CSV")
    
    uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])
    
    if uploaded_file is not None:
        try:
            df = pd.read_csv(uploaded_file)
            
            st.write(f"Loaded {{len(df)}} rows and {{len(df.columns)}} columns")
            st.dataframe(df.head())
            
            # Validate columns
            missing = [col for col in FEATURE_COLUMNS if col not in df.columns]
            if missing:
                st.error(f"Missing required columns: {{', '.join(missing)}}")
            elif st.button("🔮 Predict Batch"):
                try:
                    pipeline = load_model()
                    X = df[FEATURE_COLUMNS]
                    predictions = pipeline.predict(X)
                    
                    result_df = df.copy()
                    result_df["prediction"] = predictions
                    
                    st.success(f"✅ Generated {{len(predictions)}} predictions")
                    st.dataframe(result_df)
                    
                    # Download results
                    csv = result_df.to_csv(index=False)
                    st.download_button(
                        label="📥 Download Predictions CSV",
                        data=csv,
                        file_name="predictions.csv",
                        mime="text/csv",
                    )
                except Exception as e:
                    st.error(f"Batch prediction failed: {{str(e)}}")
        
        except Exception as e:
            st.error(f"Failed to load CSV: {{str(e)}}")


with tab3:
    st.subheader("ℹ️ Model Information")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Model", MODEL_NAME)
    with col2:
        st.metric("Task Type", TASK_TYPE.title())
    with col3:
        st.metric(PRIMARY_METRIC.title(), f"{{PRIMARY_SCORE:.4f}}")
    
    st.divider()
    
    col_info1, col_info2 = st.columns(2)
    with col_info1:
        st.write("**Input Features**")
        st.write(f"Numeric: {{len(NUMERIC_FEATURES)}}")
        for col in NUMERIC_FEATURES[:5]:
            st.caption(f"• {{col}}")
        if len(NUMERIC_FEATURES) > 5:
            st.caption(f"• ... and {{len(NUMERIC_FEATURES) - 5}} more")
    
    with col_info2:
        st.write("**Categorical Features**")
        st.write(f"Categorical: {{len(CATEGORICAL_FEATURES)}}")
        for col in CATEGORICAL_FEATURES[:5]:
            st.caption(f"• {{col}}")
        if len(CATEGORICAL_FEATURES) > 5:
            st.caption(f"• ... and {{len(CATEGORICAL_FEATURES) - 5}} more")
    
    st.divider()
    
    st.markdown("""
    ### 🚀 How to Use This Dashboard
    
    1. **Single Prediction**: Use the form in the first tab to enter feature values and get a prediction
    2. **Batch Predictions**: Upload a CSV file with the same features to get predictions for all rows
    3. **Model Info**: View details about this model and its features
    
    ### 💾 Prerequisites
    
    Make sure `model.pkl` exists in the same directory as this script:
    ```python
    import pickle
    pickle.dump(report.pipeline, open("model.pkl", "wb"))
    ```
    
    ### 📦 Dependencies
    
    Install with:
    ```bash
    pip install streamlit pandas scikit-learn
    ```
    
    ### ▶️ Run This App
    
    ```bash
    streamlit run app.py
    ```
    """)


# ─ Footer ────────────────────────────────────────────────
st.divider()
st.caption("Generated by Nexora 🎯 | https://nexoraprediction.netlify.app")
'''


def _numeric_input_block(numeric_features: list[str]) -> str:
    """Generate code for numeric input widgets."""

    lines = []
    cols = {}

    for idx, col in enumerate(numeric_features):
        col_obj = "col_left" if idx % 2 == 0 else "col_right"
        if col_obj not in cols:
            cols[col_obj] = []

        lines.append(f"""    with {col_obj}:
        numeric_inputs[{col!r}] = st.number_input(
            label={col!r},
            value=0.0,
            step=1.0,
        )""")

    return "\n".join(lines)


def _categorical_input_block(categorical_features: list[str]) -> str:
    """Generate code for categorical input widgets."""

    lines = []

    for idx, col in enumerate(categorical_features):
        col_obj = "col_left" if idx % 2 == 0 else "col_right"

        lines.append(f"""    with {col_obj}:
        categorical_inputs[{col!r}] = st.selectbox(
            label={col!r},
            options=["<select value>"],  # nexora: populate with actual unique values from training data
        )""")

    return "\n".join(lines)


def _resolve_model(
    report: NexoraReport, model_name: str | None
) -> tuple[ModelResult, ModelSpec]:
    """Resolve the target model from report."""

    if model_name is None:
        result = report.best_result
        spec = report.model_specs[result.model_id]
        return result, spec
    result = report.get_model_result(model_name)
    spec = report.get_model_spec(model_name)
    return result, spec
